/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApplicationFormPanel: typeof import('./src/components/jobs/ApplicationFormPanel.vue')['default']
    ApplicationSubmissionPanel: typeof import('./src/components/common/ApplicationSubmissionPanel.vue')['default']
    BackButton: typeof import('./src/components/common/BackButton.vue')['default']
    BulkResultDialog: typeof import('./src/components/common/BulkResultDialog.vue')['default']
    CommitteeSetupDialog: typeof import('./src/components/common/CommitteeSetupDialog.vue')['default']
    DataTable: typeof import('./src/components/common/DataTable.vue')['default']
    DocumentViewer: typeof import('./src/components/common/DocumentViewer.vue')['default']
    DrilldownDialog: typeof import('./src/components/common/DrilldownDialog.vue')['default']
    EChart: typeof import('./src/components/reports/EChart.vue')['default']
    EmptyState: typeof import('./src/components/common/EmptyState.vue')['default']
    FormField: typeof import('./src/components/candidate/FormField.vue')['default']
    GreenSheetPanel: typeof import('./src/components/jobs/GreenSheetPanel.vue')['default']
    JobOpeningForm: typeof import('./src/components/jobs/JobOpeningForm.vue')['default']
    MultiSelectFilter: typeof import('./src/components/common/MultiSelectFilter.vue')['default']
    NoticePanel: typeof import('./src/components/jobs/NoticePanel.vue')['default']
    PageHeader: typeof import('./src/components/layout/PageHeader.vue')['default']
    ProgressStepper: typeof import('./src/components/common/ProgressStepper.vue')['default']
    RecruitmentTimeline: typeof import('./src/components/common/RecruitmentTimeline.vue')['default']
    ReportChartCard: typeof import('./src/components/reports/ReportChartCard.vue')['default']
    RoleAwareSidebar: typeof import('./src/components/layout/RoleAwareSidebar.vue')['default']
    RolesPermissionsPanel: typeof import('./src/components/settings/RolesPermissionsPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionCard: typeof import('./src/components/common/SectionCard.vue')['default']
    SettingsDialog: typeof import('./src/components/layout/SettingsDialog.vue')['default']
    ShortlistingPanel: typeof import('./src/components/jobs/ShortlistingPanel.vue')['default']
    ShortlistingReviewPanel: typeof import('./src/components/common/ShortlistingReviewPanel.vue')['default']
    ShortlistingSheetDialog: typeof import('./src/components/common/ShortlistingSheetDialog.vue')['default']
    SidebarNavLink: typeof import('./src/components/layout/SidebarNavLink.vue')['default']
    StatusBadge: typeof import('./src/components/common/StatusBadge.vue')['default']
    TopBar: typeof import('./src/components/layout/TopBar.vue')['default']
    UploadField: typeof import('./src/components/candidate/UploadField.vue')['default']
  }
}
